fix compile error for swift 5.9
swift 5.9 compiler doesn't support partial consume:

```swift
error: 'self' consumed more than once
    public consuming func map<NewOutput>(
                          ^
note: consumed here
        let transform = transform
                        ^
note: consumed again here
        return .init(selector) { e in
                     ^
error: fatalError
```